### ISSUE TITLE
Adjust weights on MAP/AP metrics to reflect alt text metric

### ISSUE THREAD

**Issue by rianadutta** [Shared-Reality-Lab/IMAGE-test-graphics#12]

**Comment by jeffbl** [comment]
@rianadutta If this is still relevant, can you please provide a fuller description? I'm not sure what this is? If no longer relevant, please close.

**Comment by jeffbl** [comment]
@rianadutta ping

**Comment by rianadutta** [comment]
This can be closed, was a research area I was considering related to metrics for object detection models.
