### ISSUE TITLE
STORY: As a preprocessor developer and tester, I want to clearly see differences when comparing preprocessors

### ISSUE THREAD

**Issue by rianadutta** [Shared-Reality-Lab/IMAGE-test-graphics#14]
- [x] Rather than the entire text output, display just the name of the preprocessor and the exact differences
- [x] Create input parameter flags for specific preprocessors in testdiff.py

**Comment by rianadutta** [comment]
@jeffbl story to replace issue #7 for March 6 sprint

**Comment by jeffbl** [comment]
Story makes sense to me. The trick will be to make this generic enough that it is flexible for the future as we add new preprocessors/schemas. As I mentioned in sprint meeting today, feel free to reach out for a review/discussion once you have a plan, before implementation.

**Comment by jeffbl** [comment]
@rianadutta if this is not close to complete, should it be moved to current mar27 sprint? Is it feasible to complete it by then? If not, we should move to backlog until you can complete it within a sprint.
